<div class="ttr_block">
  <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
  <div class="ttr_block_header">
              <h3 class="ttr_block_heading">
                <?php $path = $this->getSkinUrl(); ?>
                <img src="<?php echo $path ?>images/blockicon.png">
                </img>
               <?php echo $this->__('My Account'); ?>
              </h3>
  </div>
  <div class="ttr_block_content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
  </div>
</div>