<?php $_items = $this->getItems()?>
<?php if($_items): ?>
<div class="ttr_block">
  <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
  <div class="ttr_block_header">
              <h3 class="ttr_block_heading">
                <?php $path = $this->getSkinUrl(); ?>
                <img src="<?php echo $path ?>images/blockicon.png">
                </img>
             <?php echo $this->__('My Orders') ?>
              </h3>
  </div>
  <div class="ttr_block_content">
    <form method="post" action="<?php echo $this->getFormActionUrl() ?>" id="reorder-validate-detail">
        
            <p class="block-subtitle"><?php echo $this->__('Last Ordered Items') ?></p>
            <ol id="cart-sidebar-reorder">
            <?php $_showAddButtonFlag = false ?>
            <?php foreach ($_items as $_item): ?>
                <li class="item">
                    <?php if ($this->isItemAvailableForReorder($_item)): ?>
                        <?php $_showAddButtonFlag = true ?>
                        <input type="checkbox" name="order_items[]" id="reorder-item-<?php echo $_item->getId() ?>" value="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Add to Cart') ?>" class="checkbox validate-one-required-by-name" />
                        <script type="text/javascript">
                        //<![CDATA[
                            $('reorder-item-<?php echo $_item->getId() ?>').advaiceContainer = 'cart-sidebar-reorder-advice-container';
                        //]]>
                        </script>
                    <?php endif; ?>
                    <p class="product-name"><a href="<?php echo $_item->getProduct()->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('cart-sidebar-reorder')</script>
            <div id="cart-sidebar-reorder-advice-container"></div>
            <div class="actions">
                <?php if ($_showAddButtonFlag): ?>
                <div>
		<!--	<span class="ttr_button" onmouseout="this.className='ttr_button';" onmouseover="this.className='ttr_button_hover1';"> -->
			<input type="submit" class="btn btn-default" value="<?php echo $this->__('Add to Cart')?>">
		<!--	</span> -->
                  <div style="clear:both;"></div>
			</div>
                <?php endif; ?>
                <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('View All'); ?></a>
            </div>
           </form>

<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">
//<![CDATA[
    var reorderFormDetail = new VarienForm('reorder-validate-detail');
//]]>
</script>
  </div>
</div>

<?php endif ?>
