<?php

$productscoll    = Mage::getModel('catalog/product');
	 $_productCollection = $productscoll->getCollection();
	 $_productCollection->addAttributeToFilter('status', 1);//enabled
     $_productCollection->addAttributeToFilter('visibility', 4);//catalog, search
	 $_productCollection->addAttributeToFilter('today_special', 1);
     $_productCollection->addAttributeToSelect('*');
     $_productCollection->setPageSize(1);
      $_helper = $this->helper('catalog/output');
      ?>
 <?php $_products =   $_productCollection ?>

<?php if(!$_productCollection->count()): ?>   
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p> 

<?php else: ?>
<div class="today-special">
	<p class="today-title"><?php echo $this->__('Todays Special') ?></p> 
	<?php foreach ($_products->getItems() as $_product): ?>
		 <ul class="products-grid">
					 <li class="item">
						  <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php $maxLength =20; $productName = $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name');echo substr($productName, 0, $maxLength);if(strlen($productName) >=20){echo "..";}    ?></a></h3>
						  
						  
						   <div class="products-bg">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>" width="105" height="90" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
              
                
                <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                <div class="actions">
                    <?php if ($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
						<?php $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product); ?>
                        
                        <?php if($_compareUrl) : ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        
                    </ul>
                </div>
               <?php $storeId    = Mage::app()->getStore()->getId();

						$summaryData = Mage::getModel('review/review_summary')
										->setStoreId($storeId)
										->load($_product->getId()); 

					?>
 
					<?php if($summaryData->getReviewsCount()):?>
	
							<div class="ratings">
							<?php if ($summaryData->getRatingSummary()):?>
								<div class="rating-box">
								<div class="rating" style="width:<?php echo $summaryData->getRatingSummary() ?>%"></div>
								</div>
								
							<?php endif;?>
							</div>
				  <?php endif; ?>
                
                <div class="next-product"></div>
                </div>
						  
						  
					 </li>
			 </ul>
	 <?php endforeach; ?>	 
</div>
 <?php endif ?>
