<div class="ttr_block">
  <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
  <div class="ttr_block_header">
                  <h3 class="ttr_block_heading">
                <?php $path = $this->getSkinUrl(); ?>
                <img src="<?php echo $path ?>images/blockicon.png">
                </img>
                <?php echo $this->__('Shop Categories') ?>
              </h3>
  </div>
  <div class="ttr_block_content">
        
        <ul>
         <!-- HOME BUTTON HACK -->

        <?php $_anyActive = false; foreach ($this->getStoreCategories() as $_category) { $_anyActive = $_anyActive || $this->isCategoryActive($_category); } ?>
        <li class="ttr_menu_items_parent"><a class="ttr_menu_items_parent_link<?php echo !$_anyActive ? '_active' : '' ?>"><a href="<?php echo $this->getUrl('')?>"><span><?php echo $this->__('Home') ?></span></a></li>
        <!-- HOME BUTTON HACK -->
        <?php foreach ($this->getStoreCategories() as $_category): ?>
            <?php echo $this->drawItem($_category) ?>
        <?php endforeach ?>
        </ul>
  </div>
</div>