<?php $path = $this->getSkinUrl(); ?>
<div style="clear:both;"></div>
<div class="footer-widget-area" role="complementary">
<div class="footer-widget-area_inner">
<?php $column1 = $this->getChildHtml('footerabovecolumn1'); ?>
<?php $column2 = $this->getChildHtml('footerabovecolumn2'); ?>
<?php $column3 = $this->getChildHtml('footerabovecolumn3'); ?>
<?php $column4 = $this->getChildHtml('footerabovecolumn4'); ?>
<?php
if( !empty($column1) || !empty($column2) || !empty($column3) || !empty($column4)):
?>
<div class="ttr_footer-widget-area_inner_above0">
<?php if(!empty($column1)): ?>
<div class="cell1 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerabovecolumn1'); ?>
</div>
<?php else: ?>
<div class="cell1 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-xs-block">
</div>
<?php if(!empty($column2)): ?>
<div class="cell2 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerabovecolumn2'); ?>
</div>
<?php else: ?>
<div class="cell2 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-sm-block visible-md-block visible-xs-block">
</div>
<?php if(!empty($column3)): ?>
<div class="cell3 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerabovecolumn3'); ?>
</div>
<?php else: ?>
<div class="cell3 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-xs-block">
</div>
<?php if(!empty($column4)): ?>
<div class="cell4 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerabovecolumn4'); ?>
</div>
<?php else: ?>
<div class="cell4 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-lg-block visible-sm-block visible-md-block visible-xs-block">
</div>
</div>
<div class="clearfix"></div>
<?php endif; ?>
</div>
</div>
<div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
<footer id="ttr_footer">
<div id="ttr_footer_top_for_widgets">
<div class="ttr_footer_top_for_widgets_inner">
<?php $column1=$this->getChildHtml('first-footer-widget-area'); ?>
<?php $column2=$this->getChildHtml('second-footer-widget-area'); ?>
<?php $column3=$this->getChildHtml('third-footer-widget-area'); ?>
<?php
if (!empty($column1) || !empty($column2) || !empty($column3))
?>
<div class="footer-widget-area_fixed" role="complementary">
<div style="margin:0 auto;"role="complementary">
<?php if ( !empty($column1) ) : ?>
<?php echo $this->getChildHtml('first-footer-widget-area') ?>
<div class="clearfix visible-xs"></div>
<?php else: ?>
<div id="first" class="widget-area col-lg-4 col-md-4 col-sm-4 col-xs-12">
&nbsp;
</div>
<div class="clearfix visible-xs"></div>
<?php endif; ?>
<?php if ( !empty($column2) ) : ?>
<?php echo $this->getChildHtml( 'second-footer-widget-area' ) ?>
<div class="clearfix visible-xs"></div>
<?php else: ?>
<div id="second" class="widget-area col-lg-4 col-md-4 col-sm-4 col-xs-12">
&nbsp;
</div>
<div class="clearfix visible-xs"></div>
<?php endif; ?>
<?php if ( !empty($column3) ) : ?>
<?php echo $this->getChildHtml( 'third-footer-widget-area' ) ?>
<div class="clearfix visible-lg visible-md visible-sm visible-xs"></div>
<?php else: ?>
<div id="third" class="widget-area col-lg-4 col-md-4 col-sm-4 col-xs-12">
&nbsp;
</div>
<div class="clearfix visible-lg visible-md visible-sm visible-xs"></div>
</div>
</div>
<?php endif; ?>
</div>
</div>
<div class="ttr_footer_bottom_footer">
<div class="ttr_footer_bottom_footer_inner">
<div id="ttr_copyright">
<a href="<?php echo $this->getUrl('')?>"> <?php echo $this->getCopyright() ?>
</a>
</div>
<div class="ttr_footer_links">
<?php echo $this->getChildHtml('footer_links') ?>
</div>
<div id="ttr_footer_designed_by_links">
<a href="http://templatetoaster.com" target="_self">
Magento Theme
</a>
<span id="ttr_footer_designed_by">
Designed With TemplateToaster
</span>
</div>
<a class="ttr_footer_rss" href="<?php echo $this->getUrl('rss')?>">
</a>
<a href="http://www.facebook.com/TemplateToaster"class="ttr_footer_facebook" target="_self">
</a>
<a href="http://www.templatetoaster.com"class="ttr_footer_linkedin" target="_self" >
</a>
<a href="http://twitter.com/templatetoaster"class="ttr_footer_twitter" target="_self">
</a>
<a href="http://www.templatetoaster.com"class="ttr_footer_googleplus" target="_self">
</a>
</div>
</div>
</footer>
<div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
<div class="footer-widget-area" role="complementary">
<div class="footer-widget-area_inner">
<?php $column1 = $this->getChildHtml('footerbelowcolumn1'); ?>
<?php $column2 = $this->getChildHtml('footerbelowcolumn2'); ?>
<?php $column3 = $this->getChildHtml('footerbelowcolumn3'); ?>
<?php $column4 = $this->getChildHtml('footerbelowcolumn4'); ?>
<?php
if( !empty($column1) || !empty($column2) || !empty($column3) || !empty($column4)):
?>
<div class="ttr_footer-widget-area_inner_below0">
<?php if(!empty($column1)): ?>
<div class="cell1 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerbelowcolumn1'); ?>
</div>
<?php else: ?>
<div class="cell1 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-xs-block">
</div>
<?php if(!empty($column2)): ?>
<div class="cell2 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerbelowcolumn2'); ?>
</div>
<?php else: ?>
<div class="cell2 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-sm-block visible-md-block visible-xs-block">
</div>
<?php if(!empty($column3)): ?>
<div class="cell3 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerbelowcolumn3'); ?>
</div>
<?php else: ?>
<div class="cell3 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-xs-block">
</div>
<?php if(!empty($column4)): ?>
<div class="cell4 col-lg-3 col-md-6 col-sm-6  col-xs-12">
<?php echo $this->getChildHtml('footerbelowcolumn4'); ?>
</div>
<?php else: ?>
<div class="cell4 col-lg-3 col-md-6 col-sm-6  col-xs-12"  style="background-color:transparent;">
&nbsp;
</div>
<?php endif; ?>
<div class="clearfix visible-lg-block visible-sm-block visible-md-block visible-xs-block">
</div>
</div>
<div class="clearfix"></div>
<?php endif; ?>
</div>
</div>
</div>
