<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php $path = $this->getSkinUrl(); ?>
<script type="text/javascript" src="<?php echo $path?>js/jquery.js"></script>
<script type="text/javascript">$.noConflict();</script>
<link rel="stylesheet" type="text/css" href="<?php echo $path?>css/bootstrap.css"/>
<?php echo $this->getCssJsHtml() ?>
<script>
(function() {
  var isBootstrapEvent = false;
  if (window.jQuery) {
      var all = jQuery('*');
     jQuery.each(['hide.bs.dropdown',
         'hide.bs.collapse',
         'hide.bs.modal', 
         'hide.bs.tooltip',
         'hide.bs.popover'], function(index, eventName) {
         all.on(eventName, function( event ) {
             isBootstrapEvent = true;
         });
     });
 }
 var originalHide = Element.hide;
 Element.addMethods({
     hide: function(element) {
        if(isBootstrapEvent) {
             isBootstrapEvent = false;
             return element;
         }
         return originalHide(element);
    }
 });
})();
</script>
<script type="text/javascript" src="<?php echo $path?>js/bootstrap.min.js">
</script>
<script type="text/javascript" src="<?php echo $path?>js/Customjs.js">
</script>
<script type="text/javascript" src="<?php echo $path?>js/totop.js">
</script>
<script type="text/javascript" src="<?php echo $path?>js/jquery-ui-1.10.4.custom.min.js">
</script>
<script type="text/javascript" src="<?php echo $path?>js/tt_slideshow.js">
</script>
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo $path?>js/html5shiv.js">
</script>
<script type="text/javascript" src="<?php echo $path?>js/respond.min.js">
</script>
<![endif]-->
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
