<?php global $numberofcol; ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $width=(100/$numberofcol).'%'; ?>
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg">
  <?php echo $this->__('There are no products matching the selection.') ?>
</p>
             
             <?php else: ?>

  <?php // Grid Mode ?>

  <?php $_collectionSize = $_productCollection->count() ?>
  <?php $_columnCount = $this->getColumnCount(); ?>
   <?php $i=0; foreach ($_productCollection as $_product): ?>

          <?php if ($i++%3==0): ?>
        <div style="clear:both;">
            <?php endif ?>
            
            <div  class="post_column col-lg-4 col-md-4 col-sm-4 col-xs-12">
<article style="margin-right:5px;"class="ttr_post">
<div class="ttr_post_content_inner">
<div class="ttr_article grid">
  <!--<li style="list-style:none outside none;" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">--> <!--AJAY-->
  <li>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(600,900); ?>" width="100%" height="220" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <div class="ttr_post_inner_box">
                         <h1 class="ttr_post_title">
                          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?>
                          </a>
                        </h1>
    </div>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <div class="postedon">
                          <?php if($_product->isSaleable()): ?>
                          <button style="margin-top:5px;" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn btn-default" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?>
                          </button>
                          <?php else: ?>
                          <p class="availability out-of-stock">
                            <span>
                              <?php echo $this->__('Out of stock') ?>
                            </span>
                          </p>
                          <?php endif; ?>
                          <ul style="clear:both; padding:0px;" class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li>
                              <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?>
                              </a>
                            </li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li>
                              <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?>
                              </a>
                            </li>
                            <?php endif; ?>
                          </ul>
                        </div>
                      </li>
</div> 
</div>
</article>
</div> 
  <?php if ($i%3==0 || $i==$_collectionSize): ?>
        </div>
          <?php endif ?>
          <?php endforeach ?>

<div style="clear:both;"></div>
<?php endif; ?>

