<?php if ($this->isPossibleOnepageCheckout()):?>
        <div style="clear: both;float:right;margin:10px 0;">
		<!--	<span class="ttr_button" onmouseout="this.className='ttr_button';" onmouseover="this.className='ttr_button_hover1';" onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"> -->
			<input type="submit" class="btn btn-default" value="<?php echo $this->__('Proceed to Checkout')?>" onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
   <!--   </span> -->
          <div style="clear:both;"></div>
			</div>
<?php endif?>
