<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" style="width:25px;" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
          <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart btn btn-default" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?>
          </button>
		        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
