<?php if($this->getItemCount()): ?>
<div class="ttr_post">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h1 class="ttr_post_title"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h1>
                <?php echo $this->getPriceHtml($_item, true) ?>
                 <div style="float:left;"> 
	<!--		<span class="ttr_button" onmouseout="this.className='ttr_button';" onmouseover="this.className='ttr_button_hover1';" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"> -->
			<input type="submit" class="btn btn-default" value="<?php echo $this->__('Add to Cart')?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')">
   <!--   </span> -->
      </div>
              <div class="postedon" style="clear:both;">
                <ul style="clear:both;" class="add-to-links">
                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                  <li>
                    <a href=""
                      <?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?>
                    </a>
                  </li>
                  <?php endif; ?>
                  <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                  <li>
                    <span class="separator">|</span>
                    <a href=""
                      <?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?>
                    </a>
                  </li>
                  <?php endif; ?>
                </ul>
              </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
