<?php if ($this->getIsNeedToDisplaySideBar()):?>
<div class="ttr_block">
  <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
  <div class="ttr_block_header">
                    <h3 class="ttr_block_heading">
                  <?php $path = $this->getSkinUrl(); ?>
                  <img src="<?php echo $path ?>images/blockicon.png">
                  </img>
              <?php echo $this->__('My Cart') ?>
                  </h3>
          </div>
  <div class="ttr_block_content">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <?php if ($_cartQty>0): ?>
        <div class="summary">
            <?php if ($_cartQty==1): ?>
                <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
            <?php else: ?>
                <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
            <?php endif ?>
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        </div>
    <?php endif ?>
    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
    <div class="actions">
        <?php echo $this->getChildHtml('extra_actions') ?>
            <div style="float:right;">
		<!--	<span class="ttr_button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')" onmouseout="this.className='ttr_button';" onmouseover="this.className='ttr_button_hover1';"> -->
			<input type="submit" class="btn btn-default" value="<?php echo $this->__('Checkout')?>" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')">
     <!-- </span> -->
              <div style="clear:both;"></div>
			</div>
    </div>
    <?php endif ?>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
        <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
        <ol id="cart-sidebar" class="mini-products-list">
        <?php foreach($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
  </div>
</div>
<?php endif;?>
