<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="ttr_block">
  <div style="height:0px;width:0px;overflow:hidden;-webkit-margin-top-collapse: separate;"></div>
  <div class="ttr_block_header">
    <h3 class="ttr_block_heading">
                <?php $path = $this->getSkinUrl(); ?>
                <img src="<?php echo $path ?>images/blockicon.png">
                </img>
              <?php echo $this->__('Recently Viewed Products') ?>
              </h3>
  </div>
  <div class="ttr_block_content">
      <ol id="recently-viewed-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
  </div>
</div>
<?php endif; ?>
